package com.letv.core.bean;

import com.letv.core.bean.switchinfo.AdsConfig;
import com.letv.core.bean.switchinfo.AdsInfo;
import com.letv.core.bean.switchinfo.ApiInfo;
import com.letv.core.bean.switchinfo.ChannelWorldCupInfo;
import com.letv.core.bean.switchinfo.Defaultbr;
import com.letv.core.bean.switchinfo.FreeTime;
import com.letv.core.bean.switchinfo.H265Info;
import com.letv.core.bean.switchinfo.JpushInfo;
import com.letv.core.bean.switchinfo.LogoInfo;
import com.letv.core.bean.switchinfo.PhonePayInfo;
import com.letv.core.bean.switchinfo.RecommendInfo;
import com.letv.core.bean.switchinfo.SearchWordsInfo;
import com.letv.core.bean.switchinfo.StatInfo;
import com.letv.core.bean.switchinfo.ThemeDataBean;
import com.letv.core.bean.switchinfo.TimeOutInfo;
import com.letv.core.bean.switchinfo.UpgradeInfo;
import com.letv.core.bean.switchinfo.UtpInfo;
import java.util.HashMap;

public class DataStatusInfoBean implements LetvBaseBean {
    private static final long serialVersionUID = 1;
    public boolean adOffline = false;
    public int androidOpen350 = 0;
    public String blockNum = null;
    public boolean bottomRecommendSwitch = true;
    public int channelMember = 0;
    public boolean channelRecommendSwitch = true;
    public boolean chinaUnicom = false;
    public int combine = 1;
    public int combineUseM3u8 = 0;
    public int copyright;
    public String dexpatch = "0";
    public int dlna = 1;
    public Defaultbr downloadDefaultbr;
    public int game = 0;
    public String irsDomain;
    public boolean isLinkShell = false;
    public boolean isMp4Utp = false;
    public int lebox = 1;
    public int lemall = 1;
    public String m3v = "3";
    public AdsConfig mAdsConfig = null;
    public AdsInfo mAdsInfo = null;
    public ApiInfo mApiInfo = null;
    public ChannelWorldCupInfo mChannelWorldCupInfo;
    public FreeTime mFreeTime = null;
    public H265Info mH265Info = null;
    public JpushInfo mJpushInfo = null;
    public LogoInfo mLogoInfo;
    public PhonePayInfo mPhonePayInfo;
    public SearchWordsInfo mSearchWordsInfo = null;
    public StatInfo mStatInfo = null;
    public ThemeDataBean mThemeDataBean = null;
    public TimeOutInfo mTimeOutInfo;
    public UpgradeInfo mUpgradeInfo = null;
    public UtpInfo mUtpInfo = null;
    public Defaultbr playDefaultbr;
    public boolean popRecommendSwitch = false;
    public int protobuf = 0;
    public int pushTm = 0;
    public int reactNative = 1;
    public HashMap<String, RecommendInfo> recommendInfos = null;
    public String redPacketSdk;
    public String shareWords = "0";
    public int switchStream = 1;
    public int tm;
    public int uninstallEnable = 1;
}
