package com.letv.business.flow.album.model;

public class AlbumPlayInfo {
    public long autoBfTime = 0;
    public long autoBfTimeTotal = 0;
    public String autoFirstBfTime = "";
    public long autofCount = 0;
    public long beginTime;
    public long blockTime = 0;
    public int bufferNum = 0;
    public long bufferTime = 0;
    public long combineTotalTime;
    public long currDuration;
    public long currRealTime;
    public long currTime;
    public long endTime;
    public long frontAdDuration;
    public long glsbBfTime = 0;
    public long hTime;
    public long lastTimeElapsed = 0;
    public int mActionId = 0;
    public long mAdConsumeTime = 0;
    public long mAdCount = 0;
    public String mAdUrl = "";
    public long mAdsLoadConsumeTime = 0;
    public long mAdsPlayFirstFrameTime = 0;
    public long mAdsRequestTime = 0;
    public long mAdsToalTime = 0;
    public String mBlockType = "nature";
    public int mCurrentState = -1;
    public long mDragTime = 0;
    public long mFirstBlockTime = 0;
    public int mGlsbNum;
    public boolean mHasBuffered = false;
    public boolean mHasCollectTimeToPlay = false;
    public int mIpt = 0;
    public boolean mIsAfterHomeClicked = false;
    public boolean mIsAutoClickSeekBar = true;
    public boolean mIsAutoClickSeekBarCount = false;
    public boolean mIsBuffered = false;
    public boolean mIsCload = false;
    public boolean mIsCombineAd = false;
    public boolean mIsFromAuto = false;
    public boolean mIsFromGlsb = false;
    public boolean mIsFromUser = false;
    public boolean mIsGslb;
    public boolean mIsPlayingAds = false;
    public boolean mIsShowSkipEnd = true;
    public boolean mIsSlipSeekBar = false;
    public boolean mIsStatisticsFinish = false;
    public boolean mIsStatisticsLoadTime = false;
    public boolean mIsStatisticsPlay = false;
    public boolean mIsUserClickSeekBar = false;
    public boolean mIsUserClickSeekBarCount = false;
    public boolean mPlayByTicket = false;
    public String mPlayType = "0";
    public String mPlayUrl = "";
    public int mReplayType = 1;
    public int mRetryNum = 0;
    public long mTimeForRequestRealUrlFromCde = 0;
    public long mTimeForRequestRealUrlFromUnion = 0;
    public long mTotalConsumeTime = 0;
    public long mType15 = 0;
    public long mType17 = 0;
    public long mType18 = 0;
    public long mType19 = 0;
    public long mType20 = 0;
    public long mType21 = 0;
    public long mType3 = 0;
    public long mType5 = 0;
    public long mType5_1 = 0;
    public long mType6_1 = 0;
    public int mUpdateCount = 0;
    public String mUuid;
    public String mUuidTimp;
    public String mVformat = "vformat=m3u8";
    public long mVideoLoadConsumeTime = 0;
    public String mVideoSend = "vsend=CDN";
    public String mVt = "";
    public long midAdPlayTime = -1;
    public long midDuration;
    public long timeElapsed = 0;
    public long type14 = 0;
    public long type7 = 0;
    public long type7_1 = 0;
    public long type8 = 0;
    public long type8_1 = 0;
    public long type9 = 0;
    public long userBfCount = 0;
    public long userBfTime = 0;
    public long userBfTimeTotal = 0;
    public String userFirstBfTime = "";
    public long videoTotalTime;
}
